Repository microsoft/tslint-microsoft-contrib, pull requests merged in 2018-11, with the labels that each got.

#617 Separated development docs into a CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: PR: Waiting for Feedback

#625 Added Node versions 10 and 11 to .travis.yml
  .travis.yml
Labels: Status: Awaiting More Feedback

#639 Added issue and PR templates as near-copies of TSLint core's
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/rule-suggestion.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: Waiting for Feedback

#638 Removed mentions of now-deprecated formatters from README.md
  README.md
  build-tasks/common/meta.js
  build-tasks/validate-documentation.js
Labels: PR: Waiting for Feedback

#637 Updated Configuration in README.md to refer to tslint.json
  README.md
Labels: PR: Waiting for Feedback

#542 Fix #362: Add an `allow-for-loop` option to `no-increment-decrement`
  src/noIncrementDecrementRule.ts
  src/tests/NoIncrementDecrementTests.ts
  tests/no-unnecessary-bind/tslint.json
  tests/no-unnecessary-field-initialization/tslint.json
  tests/no-unnecessary-local-variable/tslint.json
  tests/no-unnecessary-override/tslint.json
  tests/no-unsupported-browser-code/tslint.json
  tests/no-useless-files/code/tslint.json
  tests/no-useless-files/empty/tslint.json
  tests/no-useless-files/mixed comments/tslint.json
  tests/no-useless-files/multi line comments/tslint.json
  tests/no-useless-files/single line comments/tslint.json
  tests/no-var-self/default/tslint.json
  tests/underscore-consistent-invocation/default/tslint.json
  tests/underscore-consistent-invocation/static/tslint.json
  tests/use-named-parameter/tslint.json
  tests/valid-typeof/tslint.json
Labels: PR: Merge Target Branch

#647 Prepared 6.0.0-beta release
  README.md
  package-lock.json
  package.json
Labels: PR: Waiting for Feedback

#640 Remove appveyor.yml
  appveyor.yml
Labels: PR: Waiting for Reviewer
