Repository microsoft/tslint-microsoft-contrib, pull requests merged in 2018-10, with the labels that each got.

#578 Converted the giant rules list in README.md to a table
  README.md
Labels: PR: Merge Target Branch

#592 Fix Alt-text cannot be an image file name #217
  src/reactA11yImgHasAltRule.ts
  src/tests/reactA11yImgHasAltRuleTests.ts
Labels: PR: Waiting for Author

#584 Migrate from Grunt to npm scripts
  .travis.yml
  .vscode/launch.json
  Gruntfile.js
  README.md
  appveyor.yml
  build-tasks/common/files.js
  build-tasks/common/meta.js
  build-tasks/create-rule.js
  build-tasks/generate-default-tslint-json.js
  build-tasks/generate-package-json-for-npm.js
  build-tasks/generate-recommendations.js
  build-tasks/generate-rule-metadata.js
  build-tasks/generate-sdl-report.js
  build-tasks/templates/recommended_ruleset.template.js
  build-tasks/templates/rule.template.js
  build-tasks/validate-config.js
  build-tasks/validate-documentation.js
  package-lock.json
  package.json
  recommended_ruleset.js
  src/tests/ImportNameRuleTests.ts
  src/tests/NoFunctionExpressionRuleTests.ts
  src/tests/NoWithStatementTests.ts
  templates/rule-tests.snippet
  test-data/tsconfig.json
  tests/no-relative-imports/allow-siblings/test.js.lint
  tests/no-relative-imports/allow-siblings/test.ts.lint
  tests/no-relative-imports/allow-siblings/tslint.json
  tests/no-relative-imports/default/test.js.lint
  tests/no-relative-imports/default/test.ts.lint
  tests/no-relative-imports/default/tslint.json
Labels: PR: Waiting for Reviewer

#598 Fixes #280: Implements acessibility rule for required input elements
  README.md
  recommended_ruleset.js
  src/reactA11yRequiredRule.ts
  src/tests/ReactA11yRequiredRuleTests.ts
  tslint-warnings.csv
  tslint.json
Labels: PR: Waiting for Reviewer
